# -*- coding: utf-8 -*-
"""Bitcoin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ao5H7-kch15AnjKVogNz_U13FSeFZ-98
"""

import requests
from bs4 import BeautifulSoup

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split

import numpy as np

data = requests.get("https://finance.yahoo.com/quote/BTC-USD/history/").content
web = BeautifulSoup(data,'lxml')

table = web.find("tbody")

dies = []
preus = []

i = 0
for tr in table.find_all("tr"):
  td = tr.find_all("td")[4]
  preu = td.find("span").text
  preu_norm = []
  for digit in preu:
    if digit != ',':
      preu_norm.append(digit)
  preus.append(float(''.join(preu_norm)))
  dies.append(i)
  i += 1
  if i > 75:
    break

def invertir(xs):
  for i in range(int(len(xs)//2)):
    temp = xs[i]
    xs[i] = xs[len(xs) - 1 - i]
    xs[len(xs) - 1 - i] = temp
  pass

invertir(dies)
invertir(preus)

x = np.array(dies).reshape(-1,1)
y = np.array(preus)

model = LinearRegression()

dema = np.array(76).reshape(-1,1)

model.fit(x,y)

preudema = model.predict(dema)

pdemalist = preudema.tolist()

if(y.tolist()[75] > preudema[0]):
  print("El preu sera mes baix!!")
else:
  print("El preu serà més alt")